In [2]:
import gseapy as gp
import pandas as pd
import numpy as np

In [3]:
# Load the DE analysis result from DESeq2
de_results = pd.read_csv('10X_DEG_SALL2KO.csv', index_col = 0)
de_results

           names     scores  logfoldchanges  pvals  pvals_adj
0         RPL27A  84.855920        0.985773    0.0        0.0
1           RPS3  79.937580        0.925821    0.0        0.0
2          RPS13  77.675420        1.040028    0.0        0.0
3           CD81  75.229830        1.742295    0.0        0.0
4          RPS25  74.522790        1.007672    0.0        0.0
...          ...        ...             ...    ...        ...
30971      BICD1 -78.924580       -1.408491    0.0        0.0
30972  LINC02582 -81.296745       -1.817358    0.0        0.0
30973       UPP1 -87.677780       -1.531391    0.0        0.0
30974     MT-ND2 -89.606500       -0.879929    0.0        0.0
30975    MT-ND4L -92.844650       -0.986695    0.0        0.0

[30976 rows x 5 columns]

In [4]:
de_results = de_results.dropna(subset=['logfoldchanges']) # Remove rows that have NA in lop2FoldChange
de_results = de_results.sort_values(by='logfoldchanges', ascending=False) # Sort the dataframe based the log2FoldChange
gene_list = de_results[['names', 'logfoldchanges']] # Extract GeneID and log2FoldChange into a new dataframe
gene_list = gene_list.set_index('names') # Set the index into GeneID
gene_list = gene_list['logfoldchanges'] # Get the indexed list of log2FoldChange

In [5]:
gene_list

names
DKK4          21.831093
VCX2          20.978410
CST2          20.854036
OR2T6         20.533380
AC090116.1    19.990612
                ...
AC024337.1   -18.509846
Z97192.4     -18.572882
AL034351.3   -18.595594
AC012506.3   -18.804398
AC021016.3   -19.285305
Name: logfoldchanges, Length: 30976, dtype: float64

In [6]:
# Run GSEA Preranked

result_path = 'GSEA_analysis_SALL2KO_Pathways'

pre_res = gp.prerank(
    rnk=gene_list,  # Ranked gene list
    gene_sets='c2.all.v2025.1.Hs.symbols.gmt',  # Gene set database
    outdir=result_path,  # Output directory
    permutation_num=1000,  # Number of permutations
    format='png',  # Output format of figures
    seed=123  # Random seed for reproducibility
)

2025-10-22 22:56:04,966 [WARNING] Duplicated values found in preranked stats: 0.00% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

In [7]:
# This is the same as the prerank_report
gsea_results = pre_res.res2d
gsea_results

,Name,Term,ES,NES,NOM p-val,FDR q-val,FWER p-val,Tag %,Gene %,Lead_genes
0,prerank,NIKOLSKY_BREAST_CANCER_7P22_AMPLICON,-0.830501,-1.975577,0.0,0.172364,0.2,32/37,14.37%,UNCX;FOXK1;IQCE;GET4;RADIL;PAPOLB;GPER1;MAD1L1...
1,prerank,REACTOME_RESPONSE_OF_EIF2AK1_HRI_TO_HEME_DEFIC...,-0.782744,-1.827569,0.04428,1.0,0.907,7/15,13.17%,TRIB3;ATF5;DDIT3;CEBPB;GRB10;EIF2AK1;CEBPG
2,prerank,REACTOME_FORMATION_OF_DEFINITIVE_ENDODERM,0.861088,1.701152,0.003958,1.0,0.987,6/17,3.17%,LINC00261;FOXA2;SOX17;GATA6-AS1;EOMES;GATA6
3,prerank,SARTIPY_BLUNTED_BY_INSULIN_RESISTANCE_UP,0.873447,1.698894,0.001312,1.0,0.989,1/17,0.48%,MNDA
4,prerank,REACTOME_DOWNREGULATION_OF_SMAD2_3_SMAD4_TRANS...,-0.707541,-1.669015,0.0,1.0,1.0,1/31,0.33%,ATP1B4
...,...,...,...,...,...,...,...,...,...,...
5231,prerank,TOYOTA_TARGETS_OF_MIR34B_AND_MIR34C,0.100379,0.252329,1.0,1.0,1.0,146/439,47.35%,LDHA;PARM1;SLC43A3;FGFBP3;NECTIN1;MIR100HG;UGT...
5232,prerank,PULVER_FOREY_CELLCYCLE_ENRICHED_TFS_G2_M,0.095182,0.234451,1.0,1.0,1.0,91/313,43.85%,ZEB2;MEIS2;NR2F1;LEF1;ZBTB12;DACH1;NR2F2;ETS1;...
5233,prerank,PULVER_FOREY_CELLCYCLE_ENRICHED_TFS_S2,0.092632,0.229175,1.0,1.0,1.0,96/360,43.85%,ZEB2;MEIS2;NR2F1;LEF1;OTX1;ZBTB12;DACH1;NR2F2;...
5234,prerank,SANSOM_APC_MYC_TARGETS,0.090274,0.220646,1.0,1.0,1.0,44/235,34.92%,CDX2;HNF1B;TUBB2A;CITED1;KLF6;PSMB9;DHCR24;BDN...
5235,prerank,LIU_SOX4_TARGETS_DN,0.082381,0.204962,1.0,1.0,1.0,107/307,48.92%,ELF5;LDHA;PTGFR;TUBA1A;TMEM80;APLP2;HSPA8;RASS...

In [8]:
gsea_results_rankby_NES = gsea_results.sort_values(by='NES', ascending=False) # Sort base on NES score
gsea_results_rankby_NES

,Name,Term,ES,NES,NOM p-val,FDR q-val,FWER p-val,Tag %,Gene %,Lead_genes
2,prerank,REACTOME_FORMATION_OF_DEFINITIVE_ENDODERM,0.861088,1.701152,0.003958,1.0,0.987,6/17,3.17%,LINC00261;FOXA2;SOX17;GATA6-AS1;EOMES;GATA6
3,prerank,SARTIPY_BLUNTED_BY_INSULIN_RESISTANCE_UP,0.873447,1.698894,0.001312,1.0,0.989,1/17,0.48%,MNDA
5,prerank,HUMMERICH_BENIGN_SKIN_TUMOR_DN,0.816906,1.634086,0.01297,1.0,1.0,10/19,7.68%,TNNI2;MYH2;MYH8;IGFBP5;MYH4;TNNT3;COX6A2;S100A...
6,prerank,VALK_AML_WITH_FLT3_ITD,0.765865,1.619834,0.006394,1.0,1.0,14/40,9.35%,HOXA4;TRGC1;HOXB6;HOXB5;HOXA5;HOXA9;PDE4B;SELE...
7,prerank,KORKOLA_YOLK_SAC_TUMOR,0.749976,1.614893,0.0,1.0,1.0,31/63,13.20%,CST1;LINC00261;FOXA2;APOA1;SOX17;CST4;CCKBR;AP...
...,...,...,...,...,...,...,...,...,...,...
30,prerank,REACTOME_TRANSFERRIN_ENDOCYTOSIS_AND_RECYCLING,-0.68638,-1.563349,0.037915,1.0,1.0,1/30,0.13%,ATP6V1B1
19,prerank,FARMER_BREAST_CANCER_CLUSTER_3,-0.703191,-1.573683,0.113537,1.0,1.0,1/15,0.44%,PDZK1IP1
4,prerank,REACTOME_DOWNREGULATION_OF_SMAD2_3_SMAD4_TRANS...,-0.707541,-1.669015,0.0,1.0,1.0,1/31,0.33%,ATP1B4
1,prerank,REACTOME_RESPONSE_OF_EIF2AK1_HRI_TO_HEME_DEFIC...,-0.782744,-1.827569,0.04428,1.0,0.907,7/15,13.17%,TRIB3;ATF5;DDIT3;CEBPB;GRB10;EIF2AK1;CEBPG
0,prerank,NIKOLSKY_BREAST_CANCER_7P22_AMPLICON,-0.830501,-1.975577,0.0,0.172364,0.2,32/37,14.37%,UNCX;FOXK1;IQCE;GET4;RADIL;PAPOLB;GPER1;MAD1L1...

In [9]:
pre_res.plot(terms = gsea_results_rankby_NES['Term'][0:10], ofname=result_path + '/gsea_results/Higest_10_NES_enrichment_plot.pdf')

In [10]:
gsea_results_rankby_NES_qval = gsea_results_rankby_NES[gsea_results_rankby_NES['FDR q-val'] < 0.25] # 0.25 is considered as the significant threshold for FDR q-val
gsea_results_rankby_NES_qval

,Name,Term,ES,NES,NOM p-val,FDR q-val,FWER p-val,Tag %,Gene %,Lead_genes
0,prerank,NIKOLSKY_BREAST_CANCER_7P22_AMPLICON,-0.830501,-1.975577,0.0,0.172364,0.2,32/37,14.37%,UNCX;FOXK1;IQCE;GET4;RADIL;PAPOLB;GPER1;MAD1L1...

In [ ]:
pre_res.plot(terms = gsea_results_rankby_NES_qval['Term'][0:10], ofname= result_path + '/gsea_results/qval_sig_up_enrichment_plot.pdf') # GSEA plots for significanly upregulated pathways
pre_res.plot(terms = gsea_results_rankby_NES_qval['Term'][len(gsea_results_rankby_NES_qval)-10:len(gsea_results_rankby_NES_qval)], ofname= result_path + '/gsea_results/qval_sig_down_enrichment_plot.pdf') # GSEA plots for significanly downregulated pathways

In [11]:
Selected_terms = ['KEGG_PPAR_SIGNALING_PATHWAY',
                 'KEGG_MEDICUS_REFERENCE_BMP_SIGNALING_PATHWAY',
                 'KEGG_MEDICUS_REFERENCE_GF_RTK_RAS_ERK_SIGNALING_PATHWAY',
                 'KEGG_HEDGEHOG_SIGNALING_PATHWAY',
                 'KEGG_MEDICUS_REFERENCE_GF_RTK_PI3K_SIGNALING_PATHWAY',
                 'KEGG_MEDICUS_REFERENCE_WNT_SIGNALING_MODULATION_LGR_RSPO',
                 'KEGG_TGF_BETA_SIGNALING_PATHWAY']

pre_res.plot(terms = Selected_terms, ofname= result_path + '/gsea_results/Selected_pathways.pdf')