In [1]:
# This is the GSEA analysis for the basic multimapping counts

In [1]:
import gseapy as gp
import pandas as pd
import numpy as np

In [2]:
# Load the DE analysis result from DESeq2
de_results = pd.read_csv('Day_10_DEG_df.csv')
de_results

,GeneID,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
0,WASH7P,435.021784,0.063040,0.177744,0.354667,0.722839,0.948424
1,nan ENSG00000241860,207.690701,-0.204948,0.268906,-0.762156,0.445967,0.858362
2,CICP27,32.186670,-0.457597,0.424983,-1.076741,0.281596,0.759498
3,nan ENSG00000308579,94.246903,-0.790661,0.315992,-2.502156,0.012344,0.238582
4,nan ENSG00000268903,608.638480,-0.503366,0.322131,-1.562613,0.118144,0.581442
...,...,...,...,...,...,...,...
17809,ND4,272422.517216,0.205953,0.241587,0.852501,0.393936,0.832502
17810,ND5,86790.014663,0.222051,0.196828,1.128145,0.259259,0.744215
17811,ND6,17494.037394,0.227004,0.202284,1.122201,0.261777,0.745530
17812,CYTB,68856.451456,0.313296,0.276981,1.131109,0.258009,0.744095
17813,TRNP,1324.455798,-0.538731,0.234260,-2.299715,0.021464,0.303013

In [3]:
de_results = de_results.dropna(subset=['log2FoldChange']) # Remove rows that have NA in lop2FoldChange
de_results = de_results.sort_values(by='log2FoldChange', ascending=False) # Sort the dataframe based the log2FoldChange
gene_list = de_results[['GeneID', 'log2FoldChange']] # Extract GeneID and log2FoldChange into a new dataframe
gene_list = gene_list.set_index('GeneID') # Set the index into GeneID
gene_list = gene_list['log2FoldChange'] # Get the indexed list of log2FoldChange

In [9]:
gene_list

GeneID
MYCNUT                 4.155636
MUC15                  3.820762
CD80                   3.813991
nan ENSG00000302935    3.784112
CD93                   3.725292
                         ...
nan ENSG00000243501   -3.602109
CLEC2L                -3.679928
SCGB1D2               -3.977821
AGTR2                 -4.249709
nan ENSG00000255101   -4.644508
Name: log2FoldChange, Length: 17814, dtype: float64

In [13]:
# Run GSEA Preranked

result_path = 'GSEA_analysis_day_10_GO'

pre_res = gp.prerank(
    rnk=gene_list,  # Ranked gene list
    gene_sets='c5.all.v2024.1.Hs.symbols.gmt',  # Gene set database
    outdir=result_path,  # Output directory
    permutation_num=1000,  # Number of permutations
    format='png',  # Output format of figures
    seed=123  # Random seed for reproducibility
)

2025-03-17 19:35:39,204 [WARNING] Duplicated values found in preranked stats: 0.12% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

In [14]:
prerank_report = pd.read_csv(result_path + '/gseapy.gene_set.prerank.report.csv')
prerank_report

,Name,Term,ES,NES,NOM p-val,FDR q-val,FWER p-val,Tag %,Gene %,Lead_genes
0,prerank,GOBP_HEART_MORPHOGENESIS,0.654051,2.433356,0.0,0.000000,0.0,89/231,11.11%,DKK1;TMEM100;APLNR;GJA5;NRP1;BMP10;TBX2;ISL1;S...
1,prerank,GOBP_STRIATED_MUSCLE_TISSUE_DEVELOPMENT,0.637706,2.355124,0.0,0.000000,0.0,75/215,11.11%,HOPX;DKK1;PDGFRA;GJA5;ERBB4;LEF1;BMP10;TBX2;FG...
2,prerank,GOBP_CARDIAC_CHAMBER_DEVELOPMENT,0.661426,2.350067,0.0,0.000000,0.0,59/148,11.61%,APLNR;GJA5;HOXA13;NRP1;BMP10;TBX2;ISL1;HEY1;TE...
3,prerank,GOBP_MESENCHYME_MORPHOGENESIS,0.743215,2.349955,0.0,0.000000,0.0,34/60,12.15%,TMEM100;APLNR;LEF1;TBX2;ISL1;HEY1;SNAI2;ROBO2;...
4,prerank,GOBP_ARTERY_DEVELOPMENT,0.694698,2.336525,0.0,0.000000,0.0,49/98,14.48%,APLNR;GJA5;HOXA13;NRP1;COL3A1;TBX2;HEY1;EDNRA;...
...,...,...,...,...,...,...,...,...,...,...
7849,prerank,GOBP_POSITIVE_REGULATION_OF_CHROMOSOME_ORGANIZ...,-0.087131,-0.335763,1.0,1.000000,1.0,105/105,91.34%,PRAP1;RAD50;SETDB2;NABP2;PARN;CCT6A;ACTR5;MAPK...
7850,prerank,GOBP_REGULATION_OF_CHROMOSOME_ORGANIZATION,0.086323,0.321957,1.0,1.000000,1.0,51/238,28.99%,HECW2;SMARCD3;ANAPC15;NUMA1;FEN1;AXIN2;KAT2B;I...
7851,prerank,GOBP_PROTEIN_LOCALIZATION_TO_MICROTUBULE_ORGAN...,0.105242,0.301173,1.0,1.000000,1.0,36/36,89.50%,NUMA1;C2CD3;MARK4;STIL;CEP72;GOLGB1;HOOK3;RAB1...
7852,prerank,GOMF_ENDONUCLEASE_ACTIVITY_ACTIVE_WITH_EITHER_...,-0.093374,-0.297945,1.0,0.999998,1.0,36/36,90.69%,DNASE1L2;RPP25;ELAC2;NUDT16L1;POP5;APEX1;ENDOV...
7853,prerank,HP_PROMINENT_EYELASHES,0.123073,0.296322,1.0,0.999996,1.0,1/15,11.73%,DPF2

In [15]:
# This is the same as the prerank_report
gsea_results = pre_res.res2d
gsea_results

,Name,Term,ES,NES,NOM p-val,FDR q-val,FWER p-val,Tag %,Gene %,Lead_genes
0,prerank,GOBP_HEART_MORPHOGENESIS,0.654051,2.433356,0.0,0.0,0.0,89/231,11.11%,DKK1;TMEM100;APLNR;GJA5;NRP1;BMP10;TBX2;ISL1;S...
1,prerank,GOBP_STRIATED_MUSCLE_TISSUE_DEVELOPMENT,0.637706,2.355124,0.0,0.0,0.0,75/215,11.11%,HOPX;DKK1;PDGFRA;GJA5;ERBB4;LEF1;BMP10;TBX2;FG...
2,prerank,GOBP_CARDIAC_CHAMBER_DEVELOPMENT,0.661426,2.350067,0.0,0.0,0.0,59/148,11.61%,APLNR;GJA5;HOXA13;NRP1;BMP10;TBX2;ISL1;HEY1;TE...
3,prerank,GOBP_MESENCHYME_MORPHOGENESIS,0.743215,2.349955,0.0,0.0,0.0,34/60,12.15%,TMEM100;APLNR;LEF1;TBX2;ISL1;HEY1;SNAI2;ROBO2;...
4,prerank,GOBP_ARTERY_DEVELOPMENT,0.694698,2.336525,0.0,0.0,0.0,49/98,14.48%,APLNR;GJA5;HOXA13;NRP1;COL3A1;TBX2;HEY1;EDNRA;...
...,...,...,...,...,...,...,...,...,...,...
7849,prerank,GOBP_POSITIVE_REGULATION_OF_CHROMOSOME_ORGANIZ...,-0.087131,-0.335763,1.0,1.0,1.0,105/105,91.34%,PRAP1;RAD50;SETDB2;NABP2;PARN;CCT6A;ACTR5;MAPK...
7850,prerank,GOBP_REGULATION_OF_CHROMOSOME_ORGANIZATION,0.086323,0.321957,1.0,1.0,1.0,51/238,28.99%,HECW2;SMARCD3;ANAPC15;NUMA1;FEN1;AXIN2;KAT2B;I...
7851,prerank,GOBP_PROTEIN_LOCALIZATION_TO_MICROTUBULE_ORGAN...,0.105242,0.301173,1.0,1.0,1.0,36/36,89.50%,NUMA1;C2CD3;MARK4;STIL;CEP72;GOLGB1;HOOK3;RAB1...
7852,prerank,GOMF_ENDONUCLEASE_ACTIVITY_ACTIVE_WITH_EITHER_...,-0.093374,-0.297945,1.0,0.999998,1.0,36/36,90.69%,DNASE1L2;RPP25;ELAC2;NUDT16L1;POP5;APEX1;ENDOV...
7853,prerank,HP_PROMINENT_EYELASHES,0.123073,0.296322,1.0,0.999996,1.0,1/15,11.73%,DPF2

In [16]:
gsea_results_BP = gsea_results[gsea_results['Term'].str.contains('GOBP', na = False)]
gsea_results_MF = gsea_results[gsea_results['Term'].str.contains('GOMF', na = False)]
gsea_results_HP = gsea_results[gsea_results['Term'].str.contains('HP_', na = False)]
gsea_results_CC = gsea_results[gsea_results['Term'].str.contains('GOCC', na = False)]

In [7]:
gsea_results_rankby_NES = gsea_results.sort_values(by='NES', ascending=False) # Sort base on NES score
gsea_results_rankby_NES

,Name,Term,ES,NES,NOM p-val,FDR q-val,FWER p-val,Tag %,Gene %,Lead_genes
0,prerank,DESCARTES_FETAL_ADRENAL_CSH1_CSH2_POSITIVE_CELLS,0.693351,2.487736,0.0,0.0,0.0,49/157,5.48%,MUC15;CYP19A1;ERVW-1;SLC22A11;INSL4;KRT23;HOPX...
1,prerank,FAN_EMBRYONIC_CTX_BIG_GROUPS_BRAIN_ENDOTHELIAL,0.620938,2.418746,0.0,0.0,0.0,163/330,18.78%,CD93;HOPX;ERG;SLC38A3;APLNR;PECAM1;LMO2;NOSTRI...
2,prerank,GAO_LARGE_INTESTINE_ADULT_CJ_IMMUNE_CELLS,0.60312,2.38931,0.0,0.0,0.0,198/410,17.03%,CD93;CSF3R;PLVAP;APLNR;COL15A1;PECAM1;EGFLAM;L...
3,prerank,HU_FETAL_RETINA_FIBROBLAST,0.601006,2.361098,0.0,0.0,0.0,153/354,17.09%,H19;PLVAP;MIR99AHG;PDGFRA;PITX1;RSPO3;COL6A3;P...
4,prerank,FAN_EMBRYONIC_CTX_BRAIN_ENDOTHELIAL_2,0.610388,2.340313,0.0,0.0,0.0,125/270,18.88%,ITGA4;LRRC32;NID2;PGF;COL3A1;LUM;TBX2;TMEM204;...
...,...,...,...,...,...,...,...,...,...,...
149,prerank,DESCARTES_FETAL_MUSCLE_SATELLITE_CELLS,-0.565625,-1.653299,0.009852,0.155615,0.653,6/23,5.97%,ADAMTS16-DT;LINC02821;MEGF10;MT1M;OPRD1;USP44
148,prerank,DESCARTES_FETAL_HEART_VISCERAL_NEURONS,-0.510121,-1.658116,0.0,0.18534,0.64,17/43,12.50%,VGF;GNG4;NEFH;KCNK12;MYT1;PTPRR;KCNK3;CHRNB4;N...
136,prerank,DESCARTES_FETAL_PLACENTA_PAEP_MECOM_POSITIVE_C...,-0.435787,-1.692079,0.0,0.177926,0.516,27/96,10.12%,B4GALNT2;GABRP;TACSTD2;SYT14;KLK10;LAMB3;CP;MU...
92,prerank,GAO_LARGE_INTESTINE_24W_C8_GOBLET_CELL,-0.61505,-1.834733,0.002519,0.047659,0.126,11/26,11.47%,RASEF;PTPRN2;HLA-F;ATP2C2;SPDEF;CHGA;MAP7;SCNN...
49,prerank,DESCARTES_FETAL_LUNG_VISCERAL_NEURONS,-0.497123,-1.991236,0.0,0.006355,0.008,56/123,16.15%,CTNNA2;MIR124-1HG;EEF1A2;FAM200C;TUBB4A;PCDH19...

In [17]:
gsea_results_BP_rankby_NES = gsea_results_BP.sort_values(by='NES', ascending=False) # Sort base on NES score
gsea_results_MF_rankby_NES = gsea_results_MF.sort_values(by='NES', ascending=False) # Sort base on NES score
gsea_results_CC_rankby_NES = gsea_results_CC.sort_values(by='NES', ascending=False) # Sort base on NES score

In [8]:
pre_res.plot(terms = gsea_results_rankby_NES['Term'][0:10], ofname='gsea_results/Higest_10_NES_enrichment_plot.png')
pre_res.plot(terms = gsea_results_rankby_NES['Term'][len(gsea_results)-10:len(gsea_results)], ofname='gsea_results/Lowest_10_NES_enrichment_plot.png')
pre_res.plot(terms = gsea_results['Term'][0:10], ofname='gsea_results/Higest_10_FWERpval_enrichment_plot.png')
pre_res.plot(terms = gsea_results['Term'][len(gsea_results)-10:len(gsea_results)], ofname='gsea_results/Lowest_10_FWERpval_enrichment_plot.png')

In [8]:
gsea_results_rankby_NES_qval = gsea_results_rankby_NES[gsea_results_rankby_NES['FDR q-val'] < 0.25] # 0.25 is considered as the significant threshold for FDR q-val
gsea_results_rankby_NES_qval

,Name,Term,ES,NES,NOM p-val,FDR q-val,FWER p-val,Tag %,Gene %,Lead_genes
0,prerank,DESCARTES_FETAL_ADRENAL_CSH1_CSH2_POSITIVE_CELLS,0.693351,2.487736,0.0,0.0,0.0,49/157,5.48%,MUC15;CYP19A1;ERVW-1;SLC22A11;INSL4;KRT23;HOPX...
1,prerank,FAN_EMBRYONIC_CTX_BIG_GROUPS_BRAIN_ENDOTHELIAL,0.620938,2.418746,0.0,0.0,0.0,163/330,18.78%,CD93;HOPX;ERG;SLC38A3;APLNR;PECAM1;LMO2;NOSTRI...
2,prerank,GAO_LARGE_INTESTINE_ADULT_CJ_IMMUNE_CELLS,0.60312,2.38931,0.0,0.0,0.0,198/410,17.03%,CD93;CSF3R;PLVAP;APLNR;COL15A1;PECAM1;EGFLAM;L...
3,prerank,HU_FETAL_RETINA_FIBROBLAST,0.601006,2.361098,0.0,0.0,0.0,153/354,17.09%,H19;PLVAP;MIR99AHG;PDGFRA;PITX1;RSPO3;COL6A3;P...
4,prerank,FAN_EMBRYONIC_CTX_BRAIN_ENDOTHELIAL_2,0.610388,2.340313,0.0,0.0,0.0,125/270,18.88%,ITGA4;LRRC32;NID2;PGF;COL3A1;LUM;TBX2;TMEM204;...
...,...,...,...,...,...,...,...,...,...,...
149,prerank,DESCARTES_FETAL_MUSCLE_SATELLITE_CELLS,-0.565625,-1.653299,0.009852,0.155615,0.653,6/23,5.97%,ADAMTS16-DT;LINC02821;MEGF10;MT1M;OPRD1;USP44
148,prerank,DESCARTES_FETAL_HEART_VISCERAL_NEURONS,-0.510121,-1.658116,0.0,0.18534,0.64,17/43,12.50%,VGF;GNG4;NEFH;KCNK12;MYT1;PTPRR;KCNK3;CHRNB4;N...
136,prerank,DESCARTES_FETAL_PLACENTA_PAEP_MECOM_POSITIVE_C...,-0.435787,-1.692079,0.0,0.177926,0.516,27/96,10.12%,B4GALNT2;GABRP;TACSTD2;SYT14;KLK10;LAMB3;CP;MU...
92,prerank,GAO_LARGE_INTESTINE_24W_C8_GOBLET_CELL,-0.61505,-1.834733,0.002519,0.047659,0.126,11/26,11.47%,RASEF;PTPRN2;HLA-F;ATP2C2;SPDEF;CHGA;MAP7;SCNN...
49,prerank,DESCARTES_FETAL_LUNG_VISCERAL_NEURONS,-0.497123,-1.991236,0.0,0.006355,0.008,56/123,16.15%,CTNNA2;MIR124-1HG;EEF1A2;FAM200C;TUBB4A;PCDH19...

In [18]:
gsea_results_BP_rankby_NES_qval = gsea_results_BP_rankby_NES[gsea_results_BP_rankby_NES['FDR q-val'] < 0.25] # 0.25 is considered as the significant threshold for FDR q-val
gsea_results_MF_rankby_NES_qval = gsea_results_MF_rankby_NES[gsea_results_MF_rankby_NES['FDR q-val'] < 0.25] # 0.25 is considered as the significant threshold for FDR q-val
gsea_results_CC_rankby_NES_qval = gsea_results_CC_rankby_NES[gsea_results_CC_rankby_NES['FDR q-val'] < 0.25] # 0.25 is considered as the significant threshold for FDR q-val

In [20]:
gsea_results_BP_rankby_NES_qval

,Name,Term,ES,NES,NOM p-val,FDR q-val,FWER p-val,Tag %,Gene %,Lead_genes
0,prerank,GOBP_HEART_MORPHOGENESIS,0.654051,2.433356,0.0,0.0,0.0,89/231,11.11%,DKK1;TMEM100;APLNR;GJA5;NRP1;BMP10;TBX2;ISL1;S...
1,prerank,GOBP_STRIATED_MUSCLE_TISSUE_DEVELOPMENT,0.637706,2.355124,0.0,0.0,0.0,75/215,11.11%,HOPX;DKK1;PDGFRA;GJA5;ERBB4;LEF1;BMP10;TBX2;FG...
2,prerank,GOBP_CARDIAC_CHAMBER_DEVELOPMENT,0.661426,2.350067,0.0,0.0,0.0,59/148,11.61%,APLNR;GJA5;HOXA13;NRP1;BMP10;TBX2;ISL1;HEY1;TE...
3,prerank,GOBP_MESENCHYME_MORPHOGENESIS,0.743215,2.349955,0.0,0.0,0.0,34/60,12.15%,TMEM100;APLNR;LEF1;TBX2;ISL1;HEY1;SNAI2;ROBO2;...
4,prerank,GOBP_ARTERY_DEVELOPMENT,0.694698,2.336525,0.0,0.0,0.0,49/98,14.48%,APLNR;GJA5;HOXA13;NRP1;COL3A1;TBX2;HEY1;EDNRA;...
...,...,...,...,...,...,...,...,...,...,...
1679,prerank,GOBP_POSITIVE_REGULATION_OF_GLIOGENESIS,0.437453,1.373991,0.073574,0.247168,1.0,18/57,13.71%,TNFRSF1B;PTN;BMP2;MYRF;ID2;LRP2;MAG;SERPINE2;C...
1680,prerank,GOBP_NEURAL_TUBE_DEVELOPMENT,0.386694,1.373637,0.030423,0.247614,1.0,35/147,17.33%,ALDH1A2;SOX17;FOLR1;WNT5A;BMP4;WNT3A;LRP2;GSC;...
1684,prerank,GOBP_REGULATION_OF_MUSCLE_ORGAN_DEVELOPMENT,0.551592,1.372997,0.10473,0.248025,1.0,9/20,16.31%,LEF1;BMP4;JPH2;SFMBT1;LOX;SHH;TGFB1;RPL3L;SMAD3
1685,prerank,GOBP_POST_EMBRYONIC_DEVELOPMENT,0.422036,1.372711,0.04878,0.248361,1.0,24/76,21.14%,KDR;BMP4;BPNT2;SEMA3C;APOB;LHX1;HEG1;CSRNP1;DS...
1690,prerank,GOBP_NEGATIVE_REGULATION_OF_ENDOPLASMIC_RETICU...,0.556774,1.371969,0.113946,0.249273,1.0,5/17,7.41%,HYOU1;PRKN;SYVN1;CREB3L1;HERPUD1

In [22]:
gsea_results_MF_rankby_NES_qval

,Name,Term,ES,NES,NOM p-val,FDR q-val,FWER p-val,Tag %,Gene %,Lead_genes
44,prerank,GOMF_EXTRACELLULAR_MATRIX_STRUCTURAL_CONSTITUENT,0.617319,2.154594,0.0,0.000024,0.001,49/118,9.34%,COL15A1;FMOD;NID2;COL6A3;COL3A1;HAPLN1;LUM;VTN...
51,prerank,GOMF_CYTOKINE_BINDING,0.642712,2.142579,0.0,0.000042,0.002,44/89,15.91%,CCR7;CSF3R;CXCR6;ITGA4;LRRC32;ACKR2;NRP1;CNTFR...
53,prerank,GOMF_EXTRACELLULAR_MATRIX_STRUCTURAL_CONSTITUE...,0.746552,2.138864,0.0,0.000041,0.002,18/34,9.08%,COL15A1;COL6A3;COL3A1;COL5A1;COL13A1;COL11A1;C...
76,prerank,GOMF_GLYCOSAMINOGLYCAN_BINDING,0.582021,2.086259,0.0,0.000185,0.012,54/150,12.29%,RSPO2;EGFLAM;RSPO3;FGF10;NRP1;PGF;HAPLN1;CCN4;...
96,prerank,GOMF_HEPARIN_BINDING,0.598548,2.057107,0.0,0.000361,0.027,41/107,12.29%,RSPO2;RSPO3;FGF10;NRP1;PGF;CCN4;FGF9;VTN;PRELP...
...,...,...,...,...,...,...,...,...,...,...
1599,prerank,GOMF_PEPTIDE_RECEPTOR_ACTIVITY,0.456591,1.391283,0.058372,0.230418,1.0,24/50,13.58%,GPR32;GPR83;APLNR;CCKBR;LGR5;EDNRA;NPY1R;GRPR;...
1610,prerank,GOMF_CELL_ADHESION_MEDIATOR_ACTIVITY,0.436098,1.388189,0.060976,0.233861,1.0,21/60,17.19%,GLDN;ESAM;STXBP6;JAM3;TRIM29;EMILIN1;DSCAM;ITG...
1624,prerank,GOMF_I_SMAD_BINDING,0.583747,1.384953,0.072519,0.237065,1.0,5/16,16.31%,SMAD9;AXIN2;TGFB1I1;TGFBR1;SMAD3
1644,prerank,GOMF_ADRENERGIC_RECEPTOR_BINDING,0.566046,1.380682,0.104796,0.241232,1.0,9/16,17.89%,PDE4D;GRIA1;GRK2;AKAP5;ARRDC3;APLP1;RAPGEF2;AD...
1678,prerank,GOMF_GLYCOSYLTRANSFERASE_ACTIVITY,0.37232,1.374298,0.01519,0.246845,1.0,74/209,21.71%,ART4;ST8SIA4;HAS2;MGAT4A;GLT8D2;UGT3A1;ST6GALN...

In [23]:
gsea_results_CC_rankby_NES_qval

,Name,Term,ES,NES,NOM p-val,FDR q-val,FWER p-val,Tag %,Gene %,Lead_genes
45,prerank,GOCC_EXTERNAL_ENCAPSULATING_STRUCTURE,0.548634,2.153724,0.0,0.000024,0.001,129/373,11.28%,CLIC3;ADAMTS20;APOA1;MMP1;ANGPT4;COL15A1;EGFLA...
50,prerank,GOCC_ENDOPLASMIC_RETICULUM_LUMEN,0.56205,2.14302,0.0,0.000043,0.002,110/247,16.58%,APOA1;COL15A1;F5;COL6A3;COL3A1;VTN;STS;COL5A1;...
56,prerank,GOCC_COLLAGEN_CONTAINING_EXTRACELLULAR_MATRIX,0.557004,2.131801,0.0,0.000077,0.004,107/291,11.28%,ADAMTS20;APOA1;ANGPT4;COL15A1;EGFLAM;FMOD;NID2...
57,prerank,GOCC_COMPLEX_OF_COLLAGEN_TRIMERS,0.848965,2.130856,0.0,0.000075,0.004,12/18,9.08%,COL3A1;LUM;COL5A1;COL11A1;COL2A1;COL5A2;COL4A1...
90,prerank,GOCC_COLLAGEN_TRIMER,0.66237,2.067024,0.0,0.000301,0.021,27/54,10.05%,GLDN;COL15A1;COL6A3;COL3A1;LUM;COLEC12;COL5A1;...
126,prerank,GOCC_EXTERNAL_SIDE_OF_PLASMA_MEMBRANE,0.542112,2.006788,0.0,0.001103,0.105,66/203,11.40%,CD80;SLC22A11;CCR7;SELE;CSF2RB;CSF3R;CD274;CXC...
167,prerank,GOCC_BASEMENT_MEMBRANE,0.588586,1.947396,0.0,0.002952,0.306,31/79,10.32%,COL15A1;EGFLAM;NID2;VTN;MMRN2;TGFBI;COL5A1;P3H...
228,prerank,GOCC_GOLGI_LUMEN,0.588013,1.88125,0.0,0.007294,0.701,25/68,14.00%,MUC15;CGA;FMOD;LUM;VTN;HS3ST1;PRELP;WNT5A;WNT3...
271,prerank,GOCC_PROTEIN_COMPLEX_INVOLVED_IN_CELL_ADHESION,0.611983,1.840251,0.0,0.012147,0.888,24/44,16.61%,CD80;ITGA4;VTN;MMRN2;LAMA1;JAM3;ITGA5;ITGAV;EM...
401,prerank,GOCC_RECEPTOR_COMPLEX,0.457961,1.751561,0.0,0.028775,0.999,98/274,17.44%,CSF2RB;CSF3R;ITGA4;TLR4;PDGFRA;ERBB4;ZAP70;NRP...
511,prerank,GOCC_COPI_COATED_VESICLE,0.673896,1.693904,0.010118,0.046091,1.0,11/21,19.45%,PACS1;KDELR3;ARCN1;DIPK2A;SCYL1;COPB1;USE1;COP...
561,prerank,GOCC_APICAL_PART_OF_CELL,0.432721,1.672841,0.0,0.053632,1.0,100/318,17.76%,SLC22A11;SLC38A3;SLC6A19;CRB2;SLCO2B1;ENPEP;CN...
617,prerank,GOCC_BASAL_PART_OF_CELL,0.43858,1.654078,0.0,0.060719,1.0,59/229,13.58%,SLC22A11;SLC38A3;KCNJ16;AQP4;SLC40A1;ERBB4;SLC...
618,prerank,GOCC_SIDE_OF_MEMBRANE,0.418252,1.653499,0.0,0.060989,1.0,98/448,11.40%,CD80;SLC22A11;CCR7;SELE;CSF2RB;CSF3R;CPM;CD274...
714,prerank,GOCC_CELL_SUBSTRATE_JUNCTION,0.412691,1.616976,0.0,0.077195,1.0,113/407,17.50%,ITGA4;ARHGAP24;NRP1;TEK;DAB2;FLT1;MME;FLRT3;HM...
787,prerank,GOCC_SMOOTH_ENDOPLASMIC_RETICULUM,0.59796,1.591564,0.01406,0.090307,1.0,11/26,15.87%,HSD3B1;FTCD;APOB;HYOU1;SVIP;SYVN1;PPIB;CALR;HS...
794,prerank,GOCC_COPI_COATED_VESICLE_MEMBRANE,0.663971,1.589489,0.029668,0.091199,1.0,9/16,19.45%,KDELR3;ARCN1;DIPK2A;SCYL1;COPB1;COPG1;TMED7;CO...
838,prerank,GOCC_ENDOCYTIC_VESICLE_LUMEN,0.665173,1.575001,0.027778,0.099216,1.0,7/15,11.19%,APOA1;HP;APOB;HYOU1;CALR;CTSL;HSP90B1
870,prerank,GOCC_BASOLATERAL_PLASMA_MEMBRANE,0.424197,1.568266,0.002567,0.101713,1.0,45/188,13.58%,SLC38A3;KCNJ16;AQP4;SLC40A1;ERBB4;SLCO2B1;TEK;...
880,prerank,GOCC_MYOSIN_COMPLEX,0.53868,1.56602,0.026316,0.102598,1.0,12/40,13.40%,MYL4;MYO16;MYO3A;MYL7;MYL11;CGNL1;MYO18B;LIMCH...
980,prerank,GOCC_ENDOPLASMIC_RETICULUM_GOLGI_INTERMEDIATE_...,0.445527,1.53586,0.008475,0.121623,1.0,45/121,20.75%,F5;FTCD;ANPEP;MGAT4A;NUCB2;FOLR1;GALNT1;ROBO1;...
1081,prerank,GOCC_INTEGRIN_COMPLEX,0.569171,1.506656,0.038961,0.141504,1.0,12/26,13.03%,ITGA4;ITGA5;ITGAV;EMILIN1;ITGA11;ITGA10;ITGB2;...
1088,prerank,GOCC_PLATELET_ALPHA_GRANULE,0.468864,1.504763,0.022831,0.14265,1.0,19/62,13.09%,HGF;PECAM1;F5;EGF;PROS1;PCDH7;SERPINE2;TGFB2;F...
1091,prerank,GOCC_BRUSH_BORDER_MEMBRANE,0.517701,1.504391,0.037097,0.142799,1.0,16/39,17.72%,SLC6A19;FOLR1;LRP2;ATP6V0A4;TRPM6;CLTRN;PDZK1;...
1119,prerank,GOCC_MYOFILAMENT,0.612554,1.495726,0.052347,0.149571,1.0,5/17,5.65%,MYBPHL;TMOD1;TNNC1;ACTA1;MYBPC3
1141,prerank,GOCC_CONTRACTILE_MUSCLE_FIBER,0.403893,1.48938,0.005148,0.154639,1.0,48/184,16.30%,MYBPHL;BMP10;PDE4B;MYL4;FHOD3;ANKRD1;PDLIM3;MY...
1185,prerank,GOCC_LYSOSOMAL_LUMEN,0.451074,1.478993,0.025449,0.160984,1.0,17/82,10.90%,FMOD;LUM;PRELP;CSPG4;PDGFRB;APOB;CTSV;OGN;SMPD...
1242,prerank,GOCC_MEMBRANE_MICRODOMAIN,0.387929,1.464765,0.002484,0.171854,1.0,36/237,7.80%,SELE;PLVAP;PECAM1;ZAP70;S1PR1;TEK;KCND2;HAS2;C...
1247,prerank,GOCC_PLASMA_MEMBRANE_SIGNALING_RECEPTOR_COMPLEX,0.414104,1.464159,0.010914,0.171925,1.0,40/132,16.03%,CSF2RB;ITGA4;ZAP70;CNTFR;DRD1;ACVRL1;BMP2;ALCA...
1341,prerank,GOCC_ACROSOMAL_MEMBRANE,0.58108,1.445529,0.071304,0.184132,1.0,5/17,11.37%,ACRBP;MFGE8;HYAL3;SPACA6;RAB6A
1364,prerank,GOCC_PORE_COMPLEX,0.569643,1.44081,0.08557,0.187676,1.0,4/19,9.60%,C5;CD34;PLEKHA7;BCL2
1378,prerank,GOCC_ENDOPLASMIC_RETICULUM_GOLGI_INTERMEDIATE_...,0.440916,1.436991,0.041916,0.191175,1.0,26/71,21.54%,F5;FOLR1;GALNT1;ROBO1;CNIH2;CD55;GRIA1;CALR;ST...
1388,prerank,GOCC_ADHERENS_JUNCTION,0.396011,1.434953,0.008075,0.19272,1.0,48/167,17.99%,CDH5;ARHGAP24;CTNND2;TMEM204;CDH15;ESAM;CDH11;...
1390,prerank,GOCC_ENDOPLASMIC_RETICULUM_PROTEIN_CONTAINING_...,0.410655,1.433983,0.020492,0.193763,1.0,33/114,19.97%,UGT3A1;HYOU1;SYVN1;STT3A;GANAB;EXT2;SRPRA;PPIB...
1450,prerank,GOCC_CELL_CELL_JUNCTION,0.361121,1.420604,0.002334,0.205535,1.0,117/421,19.18%,PECAM1;GJA5;CRB2;CDH5;ARHGAP24;CTNND2;ZAP70;TM...
1547,prerank,GOCC_PLATELET_ALPHA_GRANULE_LUMEN,0.459431,1.39992,0.056782,0.223979,1.0,14/44,15.85%,HGF;F5;EGF;PROS1;TGFB2;FN1;FERMT3;SERPING1;ACT...
1578,prerank,GOCC_MAIN_AXON,0.457,1.395028,0.05,0.227307,1.0,9/49,5.69%,CRHBP;ROBO2;TNFRSF1B;EPB41L3;SCN2A;ADORA1;MAG;...
1580,prerank,GOCC_PLASMA_MEMBRANE_RAFT,0.412459,1.394945,0.043353,0.227126,1.0,24/90,16.29%,SELE;PLVAP;KCND2;HAS2;CDH15;CD177;EMP2;TFPI;ST...
1606,prerank,GOCC_RNAI_EFFECTOR_COMPLEX,0.522896,1.389432,0.102787,0.232332,1.0,6/25,16.26%,DNM3OS;MIR23AHG;NEAT1;MIR22HG;MIR29B2CHG;DDX6
1651,prerank,GOCC_MRNA_CLEAVAGE_AND_POLYADENYLATION_SPECIFI...,0.530987,1.378768,0.112754,0.243147,1.0,5/21,10.86%,SSU72L4;SSU72L2;SSU72L5;SSU72L1;CPSF7
1677,prerank,GOCC_EXTRINSIC_COMPONENT_OF_PLASMA_MEMBRANE,0.421282,1.374328,0.066958,0.246965,1.0,20/74,14.78%,CDH5;ZAP70;GNG11;CDH15;CDH11;GNG2;CDH8;DCHS1;C...
1686,prerank,GOCC_ENDOLYSOSOME,0.510648,1.372303,0.100707,0.248876,1.0,8/23,21.34%,TLR7;SMPD1;CTSK;CTSL;TPCN2;PCSK9;LGMN;AP2A2

In [11]:
pre_res.plot(terms = gsea_results_rankby_NES_qval['Term'][0:10], ofname= result_path + '/qval_sig_up_enrichment_plot.png') # GSEA plots for significanly upregulated pathways
pre_res.plot(terms = gsea_results_rankby_NES_qval['Term'][len(gsea_results_rankby_NES_qval)-10:len(gsea_results_rankby_NES_qval)], ofname= result_path + '/qval_sig_down_enrichment_plot.png') # GSEA plots for significanly downregulated pathways

In [19]:
pre_res.plot(terms = gsea_results_BP_rankby_NES_qval['Term'][0:10], ofname= result_path + '/GOBP_qval_sig_up_enrichment_plot.png') # GSEA plots for significanly upregulated pathways
pre_res.plot(terms = gsea_results_BP_rankby_NES_qval['Term'][len(gsea_results_BP_rankby_NES_qval)-10:len(gsea_results_BP_rankby_NES_qval)], ofname= result_path + '/GOBP_qval_sig_down_enrichment_plot.png') # GSEA plots for significanly downregulated pathways

pre_res.plot(terms = gsea_results_MF_rankby_NES_qval['Term'][0:10], ofname= result_path + '/GOMF_qval_sig_up_enrichment_plot.png') # GSEA plots for significanly upregulated pathways
pre_res.plot(terms = gsea_results_MF_rankby_NES_qval['Term'][len(gsea_results_MF_rankby_NES_qval)-10:len(gsea_results_MF_rankby_NES_qval)], ofname= result_path + '/GOMF_qval_sig_down_enrichment_plot.png') # GSEA plots for significanly downregulated pathways

pre_res.plot(terms = gsea_results_CC_rankby_NES_qval['Term'][0:10], ofname= result_path + '/GOCC_qval_sig_up_enrichment_plot.png') # GSEA plots for significanly upregulated pathways
pre_res.plot(terms = gsea_results_CC_rankby_NES_qval['Term'][len(gsea_results_CC_rankby_NES_qval)-10:len(gsea_results_CC_rankby_NES_qval)], ofname= result_path + '/GOCC_qval_sig_down_enrichment_plot.png') # GSEA plots for significanly downregulated pathways

In [12]:
pre_res.plot(terms = gsea_results_rankby_NES_qval['Term'][10:20], ofname= result_path + '/qval_sig_up_enrichment_plot_10-20.png') # GSEA plots for significanly upregulated pathways